// Local preview of the README exactly as GitHub renders it, with a theme and width switcher.
// Run: npm run preview   → http://127.0.0.1:4173
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { execFileSync, execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const PREVIEW = path.join(ROOT, '.preview');
const RAW = 'https://raw.githubusercontent.com/m55med/m55med/';
const PORT = Number(process.env.PORT) || 4173;

function ghToken() {
  if (process.env.GITHUB_TOKEN || process.env.GH_TOKEN) return process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  try {
    return execSync('gh auth token', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return '';
  }
}

const token = ghToken();
fs.mkdirSync(PREVIEW, { recursive: true });

// 1. Fresh assets, and live cards if we can reach the API.
execFileSync(process.execPath, [path.join(ROOT, 'scripts/build.mjs')], { stdio: 'inherit' });
if (token) {
  try {
    execFileSync(process.execPath, [path.join(ROOT, 'scripts/stats.mjs')], { stdio: 'inherit', env: { ...process.env, GITHUB_TOKEN: token } });
  } catch {
    console.warn('Could not refresh live cards; using whatever is in dist/.');
  }
}

// 2. Render README.md with GitHub's own renderer, so sanitization matches the real profile.
const res = await fetch('https://api.github.com/markdown', {
  method: 'POST',
  headers: {
    ...(token && { Authorization: `bearer ${token}` }),
    'Content-Type': 'application/json',
    'User-Agent': 'm55med-preview',
  },
  body: JSON.stringify({ text: fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8'), mode: 'gfm', context: 'm55med/m55med' }),
});
if (!res.ok) throw new Error(`GitHub markdown API: ${res.status} ${await res.text()}`);
const rendered = (await res.text()).replaceAll(`${RAW}main/assets/`, '/assets/').replaceAll(`${RAW}output/`, '/dist/');

async function markdownCss(theme) {
  const file = path.join(PREVIEW, `gh-${theme}.css`);
  if (!fs.existsSync(file)) {
    const css = await fetch(`https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-${theme}.css`);
    fs.writeFileSync(file, await css.text());
  }
}

// <picture> follows the OS theme, so resolve each one to a single theme for the switcher.
function forTheme(html, theme) {
  return html.replace(/<picture>([\s\S]*?)<\/picture>/g, (_, inner) => {
    const source = (inner.match(/<source[^>]*>/g) || []).find((s) => s.includes(`prefers-color-scheme: ${theme}`));
    const srcset = source?.match(/srcset="([^"]+)"/)?.[1];
    let img = inner.match(/<img[^>]*>/)[0];
    if (srcset) img = img.replace(/src="[^"]*"/, `src="${srcset}"`);
    const src = img.match(/src="([^"]+)"/)[1];
    // Loading the real counter would bump the live profile-view count on every preview.
    // GitHub proxies it through camo, so match the whole tag (data-canonical-src keeps the origin).
    if (inner.includes('komarev.com')) return '<code>profile views</code>';
    if (src.startsWith('/dist/') && !fs.existsSync(path.join(ROOT, src))) {
      return '<div class="placeholder">Generated by GitHub Actions after the first push</div>';
    }
    return img;
  });
}

const BG = { dark: '#0d1117', light: '#ffffff' };
for (const theme of ['dark', 'light']) {
  await markdownCss(theme);
  fs.writeFileSync(
    path.join(PREVIEW, `${theme}.html`),
    `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="/.preview/gh-${theme}.css">
<style>
  body { margin: 0; background: ${BG[theme]}; }
  .markdown-body { box-sizing: border-box; max-width: 878px; margin: 0 auto; padding: 24px; }
  .placeholder { margin: 8px auto; padding: 28px; border: 1px dashed #8b949e66; border-radius: 12px; color: #8b949e; font: 13px ui-monospace, monospace; }
</style></head>
<body><article class="markdown-body">${forTheme(rendered, theme)}</article></body></html>`,
  );
}

fs.writeFileSync(
  path.join(PREVIEW, 'index.html'),
  `<!doctype html><html><head><meta charset="utf-8"><title>m55med · README preview</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #010409; color: #e6edf3; font: 14px system-ui, sans-serif; }
  header { position: sticky; top: 0; z-index: 1; display: flex; gap: 16px; align-items: center; padding: 10px 16px; background: #0d1117; border-bottom: 1px solid #30363d; }
  header b { margin-right: auto; }
  .group { display: flex; border: 1px solid #30363d; border-radius: 8px; overflow: hidden; }
  button { background: none; color: inherit; border: 0; padding: 6px 12px; font: inherit; cursor: pointer; }
  button[aria-pressed="true"] { background: #1f6feb; color: #fff; }
  main { display: flex; justify-content: center; padding: 16px; }
  iframe { border: 1px solid #30363d; border-radius: 12px; height: calc(100vh - 90px); background: #fff; }
</style></head><body>
<header><b>m55med · README preview</b>
  <div class="group" data-k="theme"><button data-v="dark">Dark</button><button data-v="light">Light</button></div>
  <div class="group" data-k="width"><button data-v="878">Desktop</button><button data-v="375">Mobile</button></div>
</header>
<main><iframe title="README"></iframe></main>
<script>
  const state = { theme: 'dark', width: '878' };
  const frame = document.querySelector('iframe');
  function render() {
    frame.src = '/.preview/' + state.theme + '.html';
    frame.style.width = state.width + 'px';
    document.querySelectorAll('.group').forEach((g) =>
      g.querySelectorAll('button').forEach((b) => b.setAttribute('aria-pressed', String(state[g.dataset.k] === b.dataset.v))));
  }
  document.querySelectorAll('.group').forEach((g) =>
    g.addEventListener('click', (e) => { if (e.target.dataset.v) { state[g.dataset.k] = e.target.dataset.v; render(); } }));
  render();
</script></body></html>`,
);

// 3. Serve the repo folder (read-only, loopback only).
const TYPES = { '.html': 'text/html; charset=utf-8', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png' };
http
  .createServer((req, res) => {
    const url = decodeURIComponent(new URL(req.url, 'http://x').pathname);
    const file = path.normalize(path.join(ROOT, url === '/' ? '.preview/index.html' : url));
    const allowed = ['assets', 'dist', '.preview'].some((d) => file.startsWith(path.join(ROOT, d) + path.sep));
    if (!allowed || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      res.writeHead(404).end('Not found');
      return;
    }
    res.writeHead(200, { 'Content-Type': TYPES[path.extname(file)] || 'application/octet-stream', 'Cache-Control': 'no-store' });
    fs.createReadStream(file).pipe(res);
  })
  .listen(PORT, '127.0.0.1', () => console.log(`\nPreview: http://127.0.0.1:${PORT}\n`));
